export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const TOGGLE_MODE = "TOGGLE_MODE";
export const SET_PALETTE = "SET_PALETTE";
export const SET_PALETTE_COLOR = "SET_PALETTE_COLOR";
export const SET_PRIMARY_MAIN = "SET_PRIMARY_MAIN";
export const SET_SECONDARY_MAIN = "SET_SECONDARY_MAIN";
export const SET_ERROR_MAIN = "SET_ERROR_MAIN";
export const SET_PREFERENCES = "SET_PREFERENCES";
export const SET_SEARCH = "SET_SEARCH";

export default {
	TOGGLE_DRAWER,
	SET_PRIMARY_MAIN,
	SET_PALETTE_COLOR,
	SET_SECONDARY_MAIN,
	SET_PREFERENCES,
	SET_ERROR_MAIN,
	SET_PALETTE,
	TOGGLE_MODE,
	SET_SEARCH
};
