export const SET_NAVIGATION_ENTITLEMENT = "SET_NAVIGATION_ENTITLEMENT";
export const SET_SELECTED_NAVIGATION = "SET_SELECTED_NAVIGATION";
export const SET_GROUPS = "SET_GROUPS";


const COMMON = {
	SET_NAVIGATION_ENTITLEMENT,
	SET_SELECTED_NAVIGATION,
	SET_GROUPS
};

export default COMMON;