export const SET_NAVIGATION_ENTITLEMENT="SET_NAVIGATION_ENTITLEMENT";
export const SET_SELECTED_NAVIGATION="SET_SELECTED_NAVIGATION";
export const SET_GROUPS="SET_GROUPS";
export const SET_SOCIAL_MEDIAS="SET_SOCIAL_MEDIAS";
export const ADD_PROMISE="ADD_PROMISE";


const COMMON = {
	SET_NAVIGATION_ENTITLEMENT,
	SET_SELECTED_NAVIGATION,
	ADD_PROMISE,
	SET_GROUPS,
	SET_SOCIAL_MEDIAS
};

export default COMMON;